# Generated by Django 2.2.24 on 2021-07-12 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentExpiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(default=datetime.date.today, verbose_name='Expiry Date')),
            ],
            options={
                'verbose_name': 'Content Expiry',
            },
        ),
    ]
